# IRIS Dataset

In [41]:
import numpy as np
import pandas as pd

### 1. Load the data in the file iris.data in a 2-D array called iris.

In [42]:
iris = np.loadtxt("iris.data", delimiter=',', dtype=str)
print(iris)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

### 2. Drop column whose index=4 from the array iris.

In [43]:
print(np.delete(iris, 4, axis=1))

[['5.1' '3.5' '1.4' '0.2']
 ['4.9' '3.0' '1.4' '0.2']
 ['4.7' '3.2' '1.3' '0.2']
 ['4.6' '3.1' '1.5' '0.2']
 ['5.0' '3.6' '1.4' '0.2']
 ['5.4' '3.9' '1.7' '0.4']
 ['4.6' '3.4' '1.4' '0.3']
 ['5.0' '3.4' '1.5' '0.2']
 ['4.4' '2.9' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.4' '3.7' '1.5' '0.2']
 ['4.8' '3.4' '1.6' '0.2']
 ['4.8' '3.0' '1.4' '0.1']
 ['4.3' '3.0' '1.1' '0.1']
 ['5.8' '4.0' '1.2' '0.2']
 ['5.7' '4.4' '1.5' '0.4']
 ['5.4' '3.9' '1.3' '0.4']
 ['5.1' '3.5' '1.4' '0.3']
 ['5.7' '3.8' '1.7' '0.3']
 ['5.1' '3.8' '1.5' '0.3']
 ['5.4' '3.4' '1.7' '0.2']
 ['5.1' '3.7' '1.5' '0.4']
 ['4.6' '3.6' '1.0' '0.2']
 ['5.1' '3.3' '1.7' '0.5']
 ['4.8' '3.4' '1.9' '0.2']
 ['5.0' '3.0' '1.6' '0.2']
 ['5.0' '3.4' '1.6' '0.4']
 ['5.2' '3.5' '1.5' '0.2']
 ['5.2' '3.4' '1.4' '0.2']
 ['4.7' '3.2' '1.6' '0.2']
 ['4.8' '3.1' '1.6' '0.2']
 ['5.4' '3.4' '1.5' '0.4']
 ['5.2' '4.1' '1.5' '0.1']
 ['5.5' '4.2' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.0' '3.2' '1.2' '0.2']
 ['5.5' '3.5' '1.3' '0.2']
 

### 3. Display the shape, dimensions and size of iris.

In [44]:
print("Dimension: ",iris.ndim)
print("Shape: ",iris.shape)
print("Size: ",iris.size)

Dimension:  2
Shape:  (150, 5)
Size:  750


### 4. Split iris into three 2-D arrays, each array for a different species. Call them iris1, iris2, iris3.

In [45]:
idx1 = iris[:,-1]=='Iris-setosa'
idx2 = iris[:,-1]=='Iris-versicolor'
idx3 = iris[:,-1]=='Iris-virginica'

iris = np.delete(iris,4,axis=1)

iris = iris.astype(float)

iris1 = iris[idx1]
iris2 = iris[idx2]
iris3 = iris[idx3]

### 5. Print the three arrays iris1, iris2, iris3.

In [46]:
print("Iris 1:\n",iris1,"\n")
print("Iris 2:\n",iris2,"\n")
print("Iris 3:\n",iris3,"\n")

Iris 1:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]] 

Iris 2:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 

### 6. Create a 1-D array header having elements "Sepal Length", "Sepal Width", "Petal Length", "Petal Width", "Species No" in that order.

In [47]:
header = np.array(["Sepal Length", "Sepal Width", "Petal Length", "Petal Width", "Species No"])

irisdata = np.loadtxt('iris.data',delimiter=',',dtype=str)

irisdata = np.array(np.insert(irisdata, 0, header, axis=0))

### 7. Display the array header.

In [48]:
print(irisdata)

[['Sepal Length' 'Sepal Width' 'Petal Length' 'Petal Width' 'Species No']
 ['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2

### 8. Find the max, min, mean, and standard deviation, variance for the columns of the iris and store the results in the arrays iris_max, iris_min, iris_avg, iris_std, iris_var respectively. The results must be rounded to not more than two decimal places.

In [49]:
iris_max = np.round(np.max(iris, axis=0), 2)
iris_min = np.round(np.min(iris, axis=0), 2)
iris_avg = np.round(np.average(iris, axis=0), 2)
iris_std = np.round(np.std(iris, axis=0), 2)
iris_var = np.round(np.var(iris, axis=0), 2)

### 9. Similarly find the max, min, mean, and standard deviation, variance for the columns of iris1, iris2 and iris3. Store the results in the arrays with appropriate names.

In [50]:
iris1_max = np.round(np.max(iris1, axis=0), 2)
iris1_min = np.round(np.min(iris1, axis=0), 2)
iris1_avg = np.round(np.average(iris1, axis=0), 2)
iris1_std = np.round(np.std(iris1, axis=0), 2)
iris1_var = np.round(np.var(iris1, axis=0), 2)

iris2_max = np.round(np.max(iris2, axis=0), 2)
iris2_min = np.round(np.min(iris2, axis=0), 2)
iris2_avg = np.round(np.average(iris2, axis=0), 2)
iris2_std = np.round(np.std(iris2, axis=0), 2)
iris2_var = np.round(np.var(iris2, axis=0), 2)

iris3_max = np.round(np.max(iris3, axis=0), 2)
iris3_min = np.round(np.min(iris3, axis=0), 2)
iris3_avg = np.round(np.average(iris3, axis=0), 2)
iris3_std = np.round(np.std(iris3, axis=0), 2)
iris3_var = np.round(np.var(iris3, axis=0), 2)

### 10.Check the minimum values of Sepal Length, Sepal Width, Petal Length, Petal Width for the three species in comparision to the minimum values of Sepal Length, Sepal Width, Petal Length, Petal Width for the dataset as a whole and fill the given table with True if species value is greater than dataset value and False otherwise.

In [51]:
data = {'Iris Setosa': np.transpose(iris_min < iris1_min),
        'Iris Versicolor':np.transpose(iris_min < iris2_min),
        'Iris Virginica':np.transpose(iris_min < iris3_min)}

df=pd.DataFrame(data)

df.index=["Sepal Length", "Sepal Width", "Petal Length", "Petal Width"]

display(df)

Iris Setosa  Iris Versicolor  Iris Virginica
Sepal Length        False             True            True
Sepal Width          True            False            True
Petal Length        False             True            True
Petal Width         False             True            True

### 11. Compare Iris setosa's average Sepal Width to that of Iris virginica.

In [52]:
print('Iris Setosa Average Sepal Width is Greater than Iris Virginica: ', iris1_avg[1]>iris3_avg[1])

Iris Setosa Average Sepal Width is Greater than Iris Virginica:  True


### 12. Compare Iris setosa's average Sepal Length to that of Iris virginica.

In [53]:
print('Iris Setosa Average Petal Length is Greater than Iris Virginica: ',iris1_avg[2]>iris3_avg[2])

Iris Setosa Average Petal Length is Greater than Iris Virginica:  False


### 13. Compare Iris setosa's average Petal Width to that of Iris virginica.

In [54]:
print('Iris Setosa Average Petal Width is Greater than Iris Virginica: ',iris1_avg[3]>iris3_avg[3])

Iris Setosa Average Petal Width is Greater than Iris Virginica:  False


### 14. Save the iris_avg in a comma seperated file named IrisMeanValues.txt on the hard disk.

In [55]:
np.savetxt('IrisMeanValues.txt', [iris_avg], delimiter=", ", fmt='%.2f')

### 15. Save the iris_max, iris_avg, iris_min in a comma seperated file named IrisStat.txt on the hard disk.

In [56]:
data = [iris_max, iris_avg, iris_min]

np.savetxt('IrisStat.txt', data, delimiter=", ", fmt='%.2f')