<a href="https://colab.research.google.com/github/Tayyab7404/Data-Analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Create a one-dimensional array and perform  all operations on it.

In [ ]:
import numpy as np

arr1 = np.arange(0,21,2)
print("Array 1:")
print(arr1)

arr2 = np.linspace(0,5,11)
print("Array 2:")
print(arr2)

print()

print("Array 1 + Array 2: ",arr1 + arr2)
print("Array 1 - Array 2: ",arr1 - arr2)
print("Array 1 * Array 2: ",arr1 * arr2)
print("Array 1 / Array 2: ",arr1[1:] / arr2[1:])
print("Array 1 % Array 2: ",arr1[1:] % arr2[1:])

Array 1:
[ 0  2  4  6  8 10 12 14 16 18 20]
Array 2:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

Array 1 + Array 2:  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25. ]
Array 1 - Array 2:  [ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15. ]
Array 1 * Array 2:  [  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
Array 1 / Array 2:  [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
Array 1 % Array 2:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 2. Create multi-dimensional arrays and find its shape and dimension.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

arr = arr.reshape(3,3)

print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")

Dimension of arr: 2
Shape of arr: (3, 3)


## 3. Create a matrix full of zeros and ones.

In [ ]:
import numpy as np

mat1 = np.zeros((3,3),dtype=int)
print("Matrix with zeros:")
print(mat1)

print()

mat2 = np.full((3,3),1,dtype=float)
print("Matrix with ones:")
print(mat2)

Matrix with zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Matrix with ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 4. Reshape and flatten data in the array.

In [ ]:
import numpy as np

mat1 = np.array([1,2,3,4,5,6,7,8,9])
print("Matrix Before Reshaping:")
print(mat1)

mat1 = mat1.reshape((3,3))
print("Matrix After Reshaping:")
print(mat1)

print()

mat2 = np.array(mat1)
print("Matrix Before Flattening:")
print(mat2)

mat2 = mat2.flatten()
print("Matrix After Flattening:")
print(mat2)

Matrix Before Reshaping:
[1 2 3 4 5 6 7 8 9]
Matrix After Reshaping:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix Before Flattening:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix After Flattening:
[1 2 3 4 5 6 7 8 9]


## 5. Perform arithmetic operations on multi-dimensional arrays.

In [ ]:
import numpy as np

mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Matrix 1:")
print(mat1)
print("Matrix 2")
print(mat2)
print()
print("Matrix 1 + Matrix 2:")
print(mat1 + mat2)
print()
print("Matrix 1 - Matrix 2:")
print(mat1 - mat2)
print()
print("Matrix 1 * Matrix 2:")
print(mat1 * mat2)
print()
print("Matrix 1 / Matrix 2:")
print(mat1 / mat2)
print()
print("Matrix 1 % Matrix 2:")
print(mat1 % mat2)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix 1 + Matrix 2:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix 1 - Matrix 2:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix 1 * Matrix 2:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix 1 / Matrix 2:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Matrix 1 % Matrix 2:
[[1 2 3]
 [4 0 2]
 [1 0 0]]


## 6. Append data Vertically and Horizontally.

In [ ]:
import numpy as np

mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix Before Appending Vertically:")
print(mat1)

mat1 = np.append(mat1,[[10],[11],[12]],axis=1)
print("Matrix After Appending Vertically:")
print(mat1)

print()

mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix Before Appending Horizontally:")
print(mat2)

mat2 = np.append(mat2,[[10,11,12]],axis=0)
print("Matrix After Appending Horizontally:")
print(mat2)

Matrix Before Appending Vertically:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix After Appending Vertically:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]

Matrix Before Appending Horizontally:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix After Appending Horizontally:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 7. Apply indexing and slicing on array.

In [ ]:
import numpy as np

arr = np.random.randint(low=1,high=10,size=15,dtype=int)
print("Array: ",arr)
print(f"Element at index 3: {arr[3]}")
print(f"Element at index 7: {arr[7]}")

print(f"Elements from index 0 to 6: {arr[0:7]}")
print(f"Elements from index 2 to 8: {arr[2:9]}")

Array:  [3 5 5 2 3 4 1 9 1 8 9 2 3 4 9]
Element at index 3: 2
Element at index 7: 9
Elements from index 0 to 6: [3 5 5 2 3 4 1]
Elements from index 2 to 8: [5 2 3 4 1 9 1]


## 8. Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation.

In [ ]:
import numpy as np

arr = np.random.randint(low=1,high=10,size=15,dtype=int)
print("Array: ",arr)

print(f"Minimum = {np.amin(arr)}")
print(f"Maximum = {np.amax(arr)}")
print(f"Mean = {np.mean(arr)}")
print(f"Median = {np.median(arr)}")
print(f"Standard Deviation = {np.std(arr)}")
print(f"Variance = {np.var(arr)}")

Array:  [3 6 1 1 2 6 1 8 8 6 6 4 1 4 4]
Minimum = 1
Maximum = 8
Mean = 4.066666666666666
Median = 4.0
Standard Deviation = 2.434930982366623
Variance = 5.928888888888889


## 9. Dot matrix product of two arrays.

In [ ]:
import numpy as np

mat1 = np.random.randint(low=1,high=10,size=[3,3],dtype=int)
mat2 = np.random.randint(low=1,high=10,size=[3,3],dtype=int)

print("Matrix 1:")
print(mat1)
print()
print("Matrix 2:")
print(mat2)
print()
print("Matrix 1 * Matrix 2:")
print(np.dot(mat1,mat2))

Matrix 1:
[[1 8 9]
 [2 2 5]
 [4 2 6]]

Matrix 2:
[[1 9 5]
 [6 8 9]
 [3 8 3]]

Matrix 1 * Matrix 2:
[[ 76 145 104]
 [ 29  74  43]
 [ 34 100  56]]


## 10. Compute the Eigen values of a matrix.

In [ ]:
import numpy as np

mat = np.array([[3,1,1],[2,4,2],[1,1,3]])

print("Matrix:")
print(mat)
print()

EigVals, EigVecs = np.linalg.eig(mat)

print("Eigen Values:")
print(EigVals)

print()

print("Eigen Vectors:")
print(EigVecs)

Matrix:
[[3 1 1]
 [2 4 2]
 [1 1 3]]

Eigen Values:
[2. 6. 2.]

Eigen Vectors:
[[-0.80178373  0.40824829 -0.20234712]
 [ 0.53452248  0.81649658 -0.58387515]
 [ 0.26726124  0.40824829  0.78622227]]


## 11. Solve a linear matrix equation such as 3x + y = 9, x + 2y = 8.

In [ ]:
import numpy as np

arr1 = np.array([[3,1],[1,2]])
arr2 = np.array([9,8])

print("Equation 1: 3x + y = 9")
print("Equation 2: x + 2y = 8")

print()

sol = np.linalg.solve(arr1,arr2)

print("Solution: ")
print(f"x = {sol[0]}, y = {sol[1]}")

print()

print("Verification: ")
print(np.allclose(np.dot(arr1, sol), arr2))

Equation 1: 3x + y = 9
Equation 2: x + 2y = 8

Solution: 
x = 2.0, y = 3.0

Verification: 
True


## 12. Compute the multiplicative inverse of a matrix.

In [ ]:
import numpy as np

mat = np.array([[3,1,1],[2,4,2],[1,1,3]])

print("Matrix:")
print(mat)
print()

inv = np.linalg.inv(mat)

print("Inverse of Matrix:")
print(inv)

Matrix:
[[3 1 1]
 [2 4 2]
 [1 1 3]]

Inverse of Matrix:
[[ 0.41666667 -0.08333333 -0.08333333]
 [-0.16666667  0.33333333 -0.16666667]
 [-0.08333333 -0.08333333  0.41666667]]


## 13. Compute the rank of a matrix.

In [ ]:
import numpy as np

mat = np.array([[1,2,3],[2,3,4],[3,5,7]])

print("Matrix:")
print(mat)
print()

rank = np.linalg.matrix_rank(mat)

print("Rank of Matrix:")
print(rank)



Matrix:
[[1 2 3]
 [2 3 4]
 [3 5 7]]

Rank of Matrix:
2


## 14. Compute the determinant of matrix.

In [ ]:
import numpy as np

mat = np.array([[3,1,1],[2,4,2],[1,1,3]])

print("Matrix:")
print(mat)
print()

det = np.linalg.det(mat)

print("Determinant of Matrix:")
print(det)

Matrix:
[[3 1 1]
 [2 4 2]
 [1 1 3]]

Determinant of Matrix:
24.000000000000004


## 15. Perform transpose and change of axes operations on arrays.

In [ ]:
import numpy as np

mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print("Matrix:")
print(mat)
print()

matT = np.transpose(mat)

print("Matrix Transpose:")
print(matT)
print()

mat_ax = np.swapaxes(mat,0,1)

print("Swapped axes:")
print(mat_ax)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Swapped axes:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


## 16. Perform splitting operations on arrays.

In [29]:
import numpy as np

arr = np.arange(9).reshape(3,3)

print("Array:")
print(arr)
print()

print("Horizontal split:")
a,b,c = np.hsplit(arr,3)
print(a)
print(b)
print(c)
print()

print("Vertical split:")
a,b,c = np.vsplit(arr,3)
print(a)
print(b)
print(c)
print()

Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Horizontal split:
[[0]
 [3]
 [6]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]

Vertical split:
[[0 1 2]]
[[3 4 5]]
[[6 7 8]]

